# Generated by Django 6.0.2 on 2026-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('health_score', models.FloatField(default=0.0)),
                ('json_report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
