# Generated by Django 5.0.2 on 2026-02-28 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('WISHLIST', 'Wishlist'), ('APPLIED', 'Applied'), ('INTERVIEWING', 'Interviewing'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], default='WISHLIST', max_length=20)),
                ('job_description', models.TextField(blank=True)),
                ('match_score', models.IntegerField(default=0)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('round_number', models.IntegerField(default=1)),
                ('feedback_score', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='tracking.jobapplication')),
            ],
        ),
    ]
